# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('description', tinymce.models.HTMLField()),
                ('demo_video', models.FileField(null=True, upload_to='videos/')),
                ('district', models.CharField(max_length=100, null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
                ('cell', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('held_on', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('number_of_tickets', models.PositiveIntegerField(null=True)),
                ('duration', models.PositiveIntegerField(null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='update.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='images/avatar.jpg', upload_to='images/')),
                ('bio', tinymce.models.HTMLField()),
                ('more', tinymce.models.HTMLField()),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(default='Rwanda', max_length=100, null=True)),
                ('city', models.CharField(default='Kigali', max_length=100, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.ManyToManyField(to='update.Price')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.Price'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_category',
            field=models.ManyToManyField(to='update.Ticket'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
