# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(null=True, upload_to=b'images/')),
                ('description', tinymce.models.HTMLField()),
                ('demo_video', models.FileField(null=True, upload_to=b'videos/')),
                ('district', models.CharField(max_length=100, null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
                ('cell', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.PositiveIntegerField(null=True)),
                ('date_of_event', models.CharField(max_length=100, null=True)),
                ('time', models.TimeField(null=True, verbose_name=b'Starting time for the event')),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('event_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='update.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('number_of_tickets', models.PositiveIntegerField(null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='update.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default=b'images/avatar.jpg', upload_to=b'images/')),
                ('bio', tinymce.models.HTMLField()),
                ('more', tinymce.models.HTMLField()),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(default=b'Rwanda', max_length=100, null=True)),
                ('city', models.CharField(default=b'Kigali', max_length=100, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=100, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('number_of_tickets', models.PositiveIntegerField(null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='update.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Tpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('number_of_tickets', models.PositiveIntegerField(null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='update.Event')),
                ('ticket_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='update.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='tpayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='update.Tpayment'),
        ),
    ]
