# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_auto_20190430_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='event_category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='update.Event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
