# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0004_auto_20190430_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number_of_tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='number_of_tickets',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
