# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_auto_20190430_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket',
            field=models.ManyToManyField(null=True, to='update.Ticket'),
        ),
    ]
