# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0006_auto_20190430_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='ticket_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket',
        ),
    ]
