# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0007_auto_20190430_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='held_on',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='update.Event'),
        ),
    ]
