# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0010_tpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.PositiveIntegerField(null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('number_of_tickets', models.PositiveIntegerField(null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tpayment',
            name='number_of_tickets',
        ),
        migrations.RemoveField(
            model_name='tpayment',
            name='post_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
