# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0011_auto_20190502_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='update.Event'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tpayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='update.Tpayment'),
        ),
    ]
