# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0012_auto_20190503_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpayment',
            name='number_of_tickets',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
