# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0013_tpayment_number_of_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
